// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_JtioExsHCmex9Tq9ARiyehNaUCfK9do',
    appId: '1:1037305692644:web:255625486df32c2b7787f1',
    messagingSenderId: '1037305692644',
    projectId: 'kasol-krusade',
    authDomain: 'kasol-krusade.firebaseapp.com',
    storageBucket: 'kasol-krusade.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRbJ-g1XYvPjBG_lnN7OnRa1B5RIk5N6A',
    appId: '1:1037305692644:android:84bbcaf0bd9afe007787f1',
    messagingSenderId: '1037305692644',
    projectId: 'kasol-krusade',
    storageBucket: 'kasol-krusade.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgiOVF1EM1dwm-OJX9R_UdCLSTptR4S9M',
    appId: '1:1037305692644:ios:70f4377930f6e35c7787f1',
    messagingSenderId: '1037305692644',
    projectId: 'kasol-krusade',
    storageBucket: 'kasol-krusade.appspot.com',
    iosBundleId: 'com.example.kasolkrusade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgiOVF1EM1dwm-OJX9R_UdCLSTptR4S9M',
    appId: '1:1037305692644:ios:157645b8599b93dd7787f1',
    messagingSenderId: '1037305692644',
    projectId: 'kasol-krusade',
    storageBucket: 'kasol-krusade.appspot.com',
    iosBundleId: 'com.example.kasolkrusade.RunnerTests',
  );
}
